# Generated by Django 4.2.4 on 2023-08-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
